### ISSUE TITLE
用version 3 不是很稳定

### ISSUE THREAD

**Issue by yangxuan8282** [tangjiujun/docker-nfs-server#1]
因为树莓派的网络启动要用 nfs v3，所以尝试使用这个容器来提供，第一次确实成功了，不过经过测试发现一旦容器停止之后，除非重启宿主机，否则就无法再挂载上，这个问题有点奇怪，一开始怀疑是容器停止后端口 32765还没释放，就参照 [sjiveson/nfs-server-alpine](https://github.com/sjiveson/nfs-server-alpine/blob/master/nfsd.sh) 这里加了一下对 SIGTERM 的处理，这样修改之后容器停止之后端口确实没被占用了，不过还是挂载不上，提示协议不支持，除非重启

**Comment by tangjiujun** [comment]
按照你的描述，我测试了下这样的场景：

操作步骤：  
* 启动容器，挂载目录
* 停止容器，卸载目录
* 启动容器，重新挂在目录

测试是可以挂载成功的。

你是不是没有启动容器，或者网络环境参数没有配置正确，比如没有关闭防火墙之类的。

能否详细说一下你的操作步骤？

**Comment by yangxuan8282** [comment]
我是用的 compose 启动的，network mode 用的 host，所以没加端口了

**docker-compose.yml**

```
version: "2"

services:
  nfs:
    image: local/nfs-server
    privileged: true
    network_mode: "host"
    volumes:
      - ./exports:/etc/exports
      - ./rootfs:/nfsshare
```

另外 entrypoint 也改了一下，把指定端口的部分去掉了，之前加上去也试过，一样的结果：

```
#!/bin/bash

set -xe

trap "stop; exit 0;" SIGTERM SIGINT

stop()
{
  # We're here because we've seen SIGTERM, likely via a Docker stop command or similar
  # Let's shutdown cleanly
  echo "SIGTERM caught, terminating NFS process(es)..."
  /usr/sbin/exportfs -ua
  pid1=$(pidof rpc.nfsd)
  pid2=$(pidof rpc.mountd)
  kill -TERM $pid1 $pid2 > /dev/null 2>&1
  echo "Terminated."
  exit
}

mkdir -p /nfsshare

# Fixed nlockmgr port
#echo 'fs.nfs.nlm_tcpport=32768' >> /etc/sysctl.conf
#echo 'fs.nfs.nlm_udpport=32768' >> /etc/sysctl.conf
#sysctl -p > /dev/null

mount -t nfsd nfds /proc/fs/nfsd

rpcbind -w
rpc.nfsd -N 2 -V 3 -N 4 -N 4.1 8
exportfs -arfv

rpc.statd
rpc.mountd -N 2 -V 3 -N 4 -N 4.1 -F
```

**exports**

```
/nfsshare *(rw,fsid=0,sync,no_subtree_check,no_root_squash)
```

这是 client 上挂载用的命令：

```
sudo mount -t nfs -o vers=3 192.168.2.105:/nfsshare /tmp/nfs/
```

第一次启动是可以成功挂载的，能看到 nfs 目录里的文件：

```bash
ls /tmp/nfs/
foobar
```

停止容器后，再启动容器，就挂载不上了：

```
sudo mount -v -t nfs -o vers=3 192.168.2.105:/nfsshare /tmp/nfs/
mount.nfs: timeout set for Sun Jan  7 07:09:43 2018
mount.nfs: trying text-based options 'vers=3,addr=192.168.2.105'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: portmap query retrying: RPC: Program not registered
mount.nfs: prog 100003, trying vers=3, prot=17
mount.nfs: portmap query failed: RPC: Program not registered
mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by yangxuan8282** [comment]
看来是我的问题，我把 entrypoint.sh 的更改取消，再把 compose 里的 `network_mode: "host"` 去掉，换成端口映射就好了，现在可以正常工作的 compose：

```
version: "2"

services:
  nfs:
    image: local/nfs-server:tangjiujun
    privileged: true
    #network_mode: "host"
    ports:
      - 111:111
      - 111:111/udp
      - 2049:2049
      - 2049:2049/udp
      - 32765-32768:32765-32768
      - 32765-32768:32765-32768/udp
    volumes:
#      - ./exports:/etc/exports
      - ./rootfs:/nfsshare
``` 

重启容器后 nfs 依然可以成功挂载

谢谢分享
